// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tablesoccer.proto

package score_keeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchResult struct {
	Teams                []*MatchResult_Team `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MatchResult) Reset()         { *m = MatchResult{} }
func (m *MatchResult) String() string { return proto.CompactTextString(m) }
func (*MatchResult) ProtoMessage()    {}
func (*MatchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7adb56a5dc9f8a0, []int{0}
}

func (m *MatchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResult.Unmarshal(m, b)
}
func (m *MatchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResult.Marshal(b, m, deterministic)
}
func (m *MatchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResult.Merge(m, src)
}
func (m *MatchResult) XXX_Size() int {
	return xxx_messageInfo_MatchResult.Size(m)
}
func (m *MatchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResult.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResult proto.InternalMessageInfo

func (m *MatchResult) GetTeams() []*MatchResult_Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type MatchResult_Team struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	Score                int32     `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MatchResult_Team) Reset()         { *m = MatchResult_Team{} }
func (m *MatchResult_Team) String() string { return proto.CompactTextString(m) }
func (*MatchResult_Team) ProtoMessage()    {}
func (*MatchResult_Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7adb56a5dc9f8a0, []int{0, 0}
}

func (m *MatchResult_Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResult_Team.Unmarshal(m, b)
}
func (m *MatchResult_Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResult_Team.Marshal(b, m, deterministic)
}
func (m *MatchResult_Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResult_Team.Merge(m, src)
}
func (m *MatchResult_Team) XXX_Size() int {
	return xxx_messageInfo_MatchResult_Team.Size(m)
}
func (m *MatchResult_Team) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResult_Team.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResult_Team proto.InternalMessageInfo

func (m *MatchResult_Team) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func (m *MatchResult_Team) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Person struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Wins                 int32    `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7adb56a5dc9f8a0, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetWins() int32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7adb56a5dc9f8a0, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MatchResult)(nil), "tablesoccer.MatchResult")
	proto.RegisterType((*MatchResult_Team)(nil), "tablesoccer.MatchResult.Team")
	proto.RegisterType((*Person)(nil), "tablesoccer.Person")
	proto.RegisterType((*Empty)(nil), "tablesoccer.Empty")
}

func init() { proto.RegisterFile("proto/tablesoccer.proto", fileDescriptor_d7adb56a5dc9f8a0) }

var fileDescriptor_d7adb56a5dc9f8a0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xb6, 0xe9, 0x9f, 0xc9, 0x6d, 0x14, 0x5c, 0x82, 0x42, 0xc8, 0x29, 0x17, 0x23,
	0xb4, 0x9e, 0xbc, 0x8b, 0x87, 0x22, 0xc8, 0x46, 0xbc, 0x6f, 0x97, 0x11, 0x03, 0x49, 0x36, 0xec,
	0x8e, 0x8a, 0x5f, 0xc0, 0xab, 0x5f, 0x59, 0xba, 0xb1, 0x9a, 0x42, 0xbc, 0xed, 0x7b, 0xbf, 0xf7,
	0x66, 0x19, 0x06, 0xce, 0x3a, 0x67, 0xd9, 0x5e, 0xb1, 0xde, 0xd5, 0xe4, 0xad, 0x31, 0xe4, 0x8a,
	0xe0, 0x60, 0x3c, 0xb0, 0xb2, 0x2f, 0x01, 0xf1, 0xbd, 0x66, 0xf3, 0xa2, 0xc8, 0xbf, 0xd6, 0x8c,
	0x1b, 0x88, 0x98, 0x74, 0xe3, 0xa5, 0x48, 0xa7, 0x79, 0xbc, 0xbe, 0x28, 0x86, 0xfd, 0x41, 0xb0,
	0x78, 0x24, 0xdd, 0xa8, 0x3e, 0x9b, 0x6c, 0x61, 0xb6, 0x97, 0x78, 0x09, 0x8b, 0x8e, 0x9c, 0xb7,
	0xed, 0xa1, 0x7e, 0x72, 0x54, 0x7f, 0x08, 0x4c, 0x1d, 0x32, 0x78, 0x0a, 0x91, 0x37, 0xd6, 0x91,
	0x9c, 0xa4, 0x22, 0x8f, 0x54, 0x2f, 0xb2, 0x27, 0x98, 0xf7, 0x41, 0x3c, 0x87, 0xd5, 0x73, 0xe5,
	0x3c, 0xb7, 0xba, 0x21, 0x29, 0x52, 0x91, 0xaf, 0xd4, 0x9f, 0x81, 0x09, 0x2c, 0x6b, 0xfd, 0x03,
	0x27, 0x01, 0xfe, 0x6a, 0x44, 0x98, 0xbd, 0x57, 0xad, 0x97, 0xd3, 0x30, 0x38, 0xbc, 0xb3, 0x05,
	0x44, 0xb7, 0x4d, 0xc7, 0x1f, 0xeb, 0x4f, 0x01, 0x58, 0xee, 0xbf, 0xda, 0x12, 0x75, 0xe4, 0x4a,
	0x72, 0x6f, 0x95, 0x21, 0xbc, 0x01, 0x28, 0xd9, 0x3a, 0x0a, 0x08, 0xe5, 0x7f, 0x8b, 0x27, 0x78,
	0x44, 0xc2, 0x48, 0xbc, 0x86, 0xe5, 0x1d, 0x71, 0xdf, 0x1c, 0xdb, 0x39, 0x19, 0x33, 0x77, 0xf3,
	0x70, 0x8f, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x80, 0xe5, 0xfb, 0xaa, 0x01, 0x00,
	0x00,
}
